project_name: FGVC-HERBS
exp_name: baselineasasa
use_wandb: False
wandb_entity: ~
train_root: ./dataset/47_classes/4axes_train_90/
model_type: HERBS #resnet18 convnext HERBS
batch_size: 8
num_workers: 2
data_size: 384
backbone_model_name: swin-l
pretrained: ~
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0003
max_epochs: 50
warmup_batchs: 1500
use_amp: True
use_fpn: True
fpn_size: 1536
use_selection: True
num_selects:
  layer1: 256
  layer2: 128
  layer3: 64
  layer4: 32
use_combiner: True
lambda_b0: 1.375
lambda_b: 0.3
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 4
log_freq: 1
eval_freq:  1
temperature: 64

is_train_aug : True
isgrayscale: False
which_gpu: cuda:0
is_save_img: False
# filter dataset
is_truncate_train_dataset: False
div_num: 5
# combine bg
train_combine_bg: False
bg_path: ./bg

## cross validation
is_using_cross_validation: True
cross_validation_folds: 5