project_name: FGVC-HERBS
notes: 'no inverse'
exp_name: test
use_wandb: True
wandb_entity: ~
train_root: ./dataset/M11/train/90/
val_root: ./CUB200-2011/test/
data_size: 384
num_workers: 2
batch_size: 8
backbone_model_name: swin-t
pretrained: ~
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0003
max_epochs: 100
warmup_batchs: 1500
use_amp: True
use_fpn: True
fpn_size: 1536
use_selection: True
num_selects: 
  layer1: 256
  layer2: 128
  layer3: 64
  layer4: 32
use_combiner: True
lambda_b0: 1.375
lambda_b: 0.3
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 4
log_freq: 1
eval_freq:  1
temperature: 64
add_hands: True
is_train_aug : True
combine_hands_path : ./combine_hands/