project_name: ssl_swin-l
train_root: ./dataset/MVImgNet_dataset/
max_epochs: 10
max_lr: 0.0001
wdecay: 0.0005
num_workers: 2
batch_size: 2
pretrained: True
warmup_batchs: 1500
use_wandb: True
wandb_entity: -
model_name: MVImgNet_test
data_size: 384
optimizer: SGD
use_amp: True
eval_freq: 1
isgrayscale: False
isTrainSSL: False
which_gpu: cuda:0